name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger this pipeline on changes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use an Ubuntu environment to run the workflow

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      # Step 4: Run tests
      - name: Run Tests
        run: |
          python manage.py test  # Run Django tests to make sure everything works
